/*
 * @lc app=leetcode id=389 lang=cpp
 *
 * [389] Find the Difference
 *
 * https://leetcode.com/problems/find-the-difference/description/
 *
 * algorithms
 * Easy (58.11%)
 * Total Accepted:    444.8K
 * Total Submissions: 737K
 * Testcase Example:  '"abcd"\n"abcde"'
 *
 * You are given two strings s and t.
 * 
 * String t is generated by random shuffling string s and then add one more
 * letter at a random position.
 * 
 * Return the letter that was added to t.
 * 
 * 
 * Example 1:
 * 
 * 
 * Input: s = "abcd", t = "abcde"
 * Output: "e"
 * Explanation: 'e' is the letter that was added.
 * 
 * 
 * Example 2:
 * 
 * 
 * Input: s = "", t = "y"
 * Output: "y"
 * 
 * 
 * 
 * Constraints:
 * 
 * 
 * 0 <= s.length <= 1000
 * t.length == s.length + 1
 * s and t consist of lowercase English letters.
 * 
 * 
 */

#include "common.hpp"

class Solution {
public:
    char findTheDifference(string s, string t) {
        std::vector<int> count_s(26, 0);
        std::vector<int> count_t(26, 0);
        for (char c: s) {
            count_s[c - 'a'] += 1;
        }
        for (char c: t) {
            count_t[c - 'a'] += 1;
        }
        for (int i = 0; i < 26; i++) {
            if (count_s[i] != count_t[i]) {
                return (char) (i + 'a');
            }
        }
        return '-'; // impossible to reach
    }
};
